=== RUN   TestConstWithPrecision
--- PASS: TestConstWithPrecision (0.00s)
	const_test.go:30: message 0: 1E+2
	const_test.go:30: message 1: 1E+2
	const_test.go:30: message 2: 1.2E+2
	const_test.go:30: message 3: 123.5
	const_test.go:30: message 4: 123.5
	const_test.go:30: message 5: 123.45679
	const_test.go:30: message 6: 123.45679
	const_test.go:30: message 7: 123.45679
	const_test.go:30: message 8: 123.45679
	const_test.go:30: message 9: 123.456789
	const_test.go:30: message 10: 123.456789
	const_test.go:30: message 11: 123.456789
=== RUN   TestConstBlah
--- PASS: TestConstBlah (0.00s)
	const_test.go:48: log 1E+2: 0
	const_test.go:48: log 1E+2: 1
	const_test.go:48: log 1.2E+2: 2
	const_test.go:48: log 123.5: 3
	const_test.go:48: log 123.5: 4
	const_test.go:48: log 123.45679: 5
	const_test.go:48: log 123.45679: 6
	const_test.go:48: log 123.45679: 7
	const_test.go:48: log 123.45679: 8
	const_test.go:48: log 123.456789: 9
	const_test.go:48: log 123.456789: 10
	const_test.go:48: log 123.456789: 11
=== RUN   TestConstError
--- FAIL: TestConstError (0.00s)
	const_test.go:56: nope
=== RUN   TestConstSub
=== RUN   TestConstSub/subtest
panic: hi [recovered]
	panic: hi

goroutine 9 [running]:
panic(0x5a7ea0, 0xc42000fc10)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420242a80)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x5a7ea0, 0xc42000fc10)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/apd.TestConstSub.func1(0xc420242a80)
	/home/mjibson/src/github.com/cockroachdb/apd/const_test.go:62 +0xfb
testing.tRunner(0xc420242a80, 0x605568)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	github.com/cockroachdb/apd	0.008s
